- src/funnies.js
As described in https://github.com/1egoman/funnies/issues/6
Hope you like it! Please feel free to comment for any deletions / edits.
> Adding more funny funnies!

- src/funnies.js
Laughing at the expense of Mr. Trump.
> new funny added

- src/funnies.js
> Another funny line ✨

- src/funnies.js
> feat: Add more funnies

- src/funnies.js
Per issue #6 can adding more funnies!
> Add more funnies

- src/funnies.js
Added some more funnies and fixed typos. This is related to #6
> Updated funnies.js

- README.md
> No hidden conditions under asterisks.

- src/funnies.js
Add more funny phrases for issue  #6 .
I'll think of more and add then - they'll probably be phrases involving project managers and schedules. :)
> Adding funny phrases

- src/funnies.js
> Add new funnies

- src/funnies.js
#8  new funny quotes in src/funnies.js
> Adding new funny quotes

- README.md
- docs/index.html
- package.json
- src/react.js
Trimmed:
- `radium`
- `uglifyjs`
Added example styles to readme too!
> Trim a few modules that are no longer required

- src/funnies.js
> This is a joke.

- src/funnies.js
> code: remove duplicate funny

- src/funnies.js
for issue #6: added some funny phrases.. my first pull request / contribution to an open source project.
> for issue #6: added some funny phrases

- src/funnies.js
> Funnies additions

- src/funnies.js
The last funnie may not be wanted on websites where you are supposed to read the Terms and Conditions.😉
> Added 4 funnies.

- src/funnies.js
Added a new entry to improve product. :)
> Extended list

- src/funnies.js
Because you can't have enough of Chuck Norris
> Add more jokes

- src/funnies.js
Added five phrases to the end.
> Added new phrases

- src/funnies.js
https://github.com/1egoman/funnies/issues/6
> Office Space funny

- src/funnies.js
> Add some phrases
